Task jdp190701 21
interceptor2048/project-jdp-1907-01 pull request #13
Opened 2019-07-26 08:28 UTC by pfilar

2019-07-26 08:43 UTC, nucly requested changes

2019-07-26 08:43 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/dto/Product.java
> +//@AllArgsConstructor
Moim zdaniem mozemy spokojnie tutaj uzyc lmobok, tak samo zrobic w moim comicie dla User. Jedyne co by bylo dodac to konstruktor ze wszystkimi polami procz id.

2019-07-26 08:43 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/dto/Product.java
>      private  int id;
Proponuje tutaj wrapper Long zamiast id.

2019-07-26 08:43 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/dto/Product.java
> +    @Column(name = "id", unique = true)
Na czacie wczesniej rozmawialismy ze moznaby zostawic nazewienictwo column dla hibernate. Takze annotacja @Column jest zbedna. I tak przy okazji z tego co mi wiadomo to przy id nie trzeba uzywac unique = true, poniewaz @Id jako PRIMIARY KEY jest juz z automatu ustawione na unique.

2019-07-26 08:43 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +//@NoArgsConstructor
Tutaj tez mozna zostawic tylko lombok

2019-07-26 09:34 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/dto/Product.java
>      private int groupId;
Tutaj bedzie potrzebne chyba `private Group group;` poniewaz potrzebujemy @ManyToOne oraz @JoinColumn dla klasy Group.

2019-07-26 09:36 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
>      private double price;
Proponuje BigDecimal

2019-07-26 17:33 UTC, pfilar commented on src/main/java/com/kodilla/ecommercee/dto/Product.java
>      private int groupId;
Rozumiem, że mówisz o klasie Group w "domain", ale jeszcze nie jest utworzona

2019-07-28 08:55 UTC, nucly commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +    public List<Product> mapToProduct(final  List<ProductDto> productDtoList) {
mapToProductList  zeby bylo wiadomo o co chodzi

2019-07-28 08:55 UTC, nucly commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                productDto.getGroupId());
Hej, tutaj probujesz wrzucic Long groupId do klasy Product ktora nie bedzie miala tego pola. W klasie Product bedziesz mial private Group group. 

Proponuje stworzyc metode, ktora wyciagnie Group z bazy danych np
`private getGroupById(Long id) { [db service i wyciagniecie grupy przez id] }`

i wtedy w mapperze u gory zamiast productDto.getGroupId() po prostu

`getGroupById(productDto.getGroupId())`

W mapToProductDto natomiast productDto.getGroup().getId().

2019-07-28 12:15 UTC, nucly requested changes

2019-07-28 12:15 UTC, nucly commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +    private ProductGroupDto productGroupDto;
Wczesniej bylo dobrze, ma byc private Long groupId

2019-07-29 12:03 UTC, nucly approved these changes

2019-07-30 17:55 UTC, MarcinNidecki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @JoinColumn(name = "groupId", referencedColumnName = "id")
Wydaje mi się że skoro mamy adnotację
 @ID 
w Encji Group przy polu Long id umieszczenie tego jest zbędne.  Co o tym sądzisz?

2019-07-30 18:17 UTC, MarcinNidecki requested changes

2019-07-30 18:17 UTC, MarcinNidecki commented on src/main/java/com/kodilla/ecommercee/dto/ProductDto.java
> +    private ProductGroupDto productGroupDto;
zgadzam się powinno tu być  Long groupId.
jeśli zwrócimy JSONA  np za pomocą getProductById(2) 
zwrócisz nam w jsonie  produkt który zawiera  obiekt  ProductGruopDto
Obiekt ten może zaś zawierać listę 2000 produktów i otrzymamy długi i brzydki JSON! 

Zresztą wystarczy wrócić do specyfikacji product:

{
    "id": 1,
    "name": "kurtka zimowa",
    "description": "Pellentesque tempus interdum quam ut rhoncus. Donec ullamcorper turpis dolor. Donec euismod pretium eros et eleifend. Aliquam vulputate faucibus lorem non auctor. Vivamus erat turpis, molestie a nisl non, scelerisque luctus enim. Nunc mi mi, laoreet ac mollis nec, pharetra sit amet tortor. Vivamus a bibendum purus.",
    "price": 100,
    "groupId": "1"
}

Oczywiście  w związku z zmianą do zmiany będzie również mapper.

2019-07-31 11:46 UTC, closed without merging