Jdp190701 12
interceptor2048/project-jdp-1907-01 pull request #14
Opened 2019-07-26 17:50 UTC by mrasinski

Dodałem Encję Produktu i jego repozytorium, na razie zakomentowałem groupId, ponieważ nie przechodziły mi testy przy gradlew build, poczekam aż Group zostanie dodana do mastera

2019-07-26 17:53 UTC, a-leja approved these changes

2019-07-27 07:07 UTC, nucly requested changes

2019-07-27 07:07 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Long groupId;
Tutaj bedzie private Group group z @OneToOne i @JoinColumn

2019-07-27 07:13 UTC, mrasinski commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Long groupId;
No właśnie dzisiaj mnie naszła ta sama myśl, żeby zmienić na Group tylko nie jestem do końca przekonany czy @OnetoOne czy @ManytoOne, każdy produkt będzie miał jedną grupę?

2019-07-27 08:10 UTC, dazz4 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Long groupId;
Mozna zrobic tak, albo tak. Twoj wybor :)

2019-07-28 08:08 UTC, nucly approved these changes
Wszystko ok

2019-07-28 10:53 UTC, merged